# Generated by Django 2.0.3 on 2018-03-28 23:02

import django.contrib.auth.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='c_plus_plus',
        ),
        migrations.RemoveField(
            model_name='user',
            name='java',
        ),
        migrations.RemoveField(
            model_name='user',
            name='other_language',
        ),
        migrations.RemoveField(
            model_name='user',
            name='python',
        ),
        migrations.RemoveField(
            model_name='user',
            name='standard_c',
        ),
        migrations.AddField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status'),
        ),
        migrations.AlterField(
            model_name='user',
            name='developer',
            field=models.IntegerField(choices=[(1, 'Regular User'), (2, 'Python'), (3, 'Java'), (4, 'C'), (5, 'C++'), (6, 'Ruby'), (7, 'Go'), (8, 'Web Developer'), (9, 'Other Language')], default='1'),
        ),
    ]
